title: Alexander Schaefer
locale: "en-US"

remote_theme: mmistakes/minimal-mistakes@4.28.0
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache
  - jekyll-feed

include:
  - _pages

atom_feed:
  hide: true

footer:
  links:
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:aschaef@seas.upenn.edu"

after_footer_scripts:
  - /assets/js/color-scheme-toggle.js

author:
  name: Alexander Schaefer
  avatar: /assets/images/headshot.jpg
  bio: "I am a PhD student at UPenn with an interest in co-design of memory arrays and hardware accelerators."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:aschaef@seas.upenn.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/a-schaef"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/a-schaef"

navigation:
  main:
    - title: "About"
      url: /
    - title: "Publications"
      url: /publications/
    - title: "CV"
      url: /cv/